"""Add has_attachment to materials

Revision ID: 3c6c5853daac
Revises: 40f22b9f4671
Create Date: 2025-03-19 15:38:24.474266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6c5853daac'
down_revision: Union[str, None] = '40f22b9f4671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('has_attachment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'has_attachment')
    # ### end Alembic commands ###
