"""update attachment model fields

Revision ID: c8680f5ba578
Revises: 3c6c5853daac
Create Date: 2025-03-20 10:42:13.156745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8680f5ba578'
down_revision: Union[str, None] = '3c6c5853daac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('original_url', sa.String(), nullable=True))
    op.drop_column('attachments', 'file_url')
    op.drop_column('attachments', 'expires_at')
    op.drop_column('materials', 'has_attachment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('has_attachment', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('attachments', 'original_url')
    # ### end Alembic commands ###
